// Pruebas de firestore.rules con el emulador:
//   npx firebase emulators:exec --only firestore "node tests/rules.test.mjs"
import { readFileSync } from 'node:fs';
import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { doc, getDoc, setDoc, updateDoc, deleteDoc, collection, getDocs, writeBatch, serverTimestamp, increment, addDoc, query, where, orderBy, limit, documentId, Timestamp } from 'firebase/firestore';

const env = await initializeTestEnvironment({ projectId: 'tuki-speak', firestore: { rules: readFileSync(new URL('../firestore.rules', import.meta.url), 'utf8'), host: '127.0.0.1', port: 8085 } });
let pass = 0, fail = 0;
async function t(name, p) { try { await p; pass++; console.log('PASS', name); } catch (e) { fail++; console.log('FAIL', name, e.message); } }
const ana = env.authenticatedContext('ana').firestore(), bob = env.authenticatedContext('bob').firestore(), anon = env.unauthenticatedContext().firestore();
const keys = { v: 1, alg: 'PBKDF2-SHA256/AES-GCM-256', salt: 'A'.repeat(22), iv: 'B'.repeat(16), ct: 'C'.repeat(200), iter: 310000 };
const meta = { schemaVersion: 1, updatedAt: Date.now(), device: 'Chrome · Android', progressSize: 1234, app: 'tuki-speak' };
const now = Date.now();

await t('owner creates meta', assertSucceeds(setDoc(doc(ana, 'users/ana'), meta)));
await t('owner writes batch (progress + settings + meta with keysEnc) like the app', (async () => { const b = writeBatch(ana);
  b.set(doc(ana, 'users/ana/data/progress'), { z: 'abc', enc: 'TK1', n: 3, updatedAt: now }); b.set(doc(ana, 'users/ana/data/settings'), { s: { goal: 20, theme: 'dark' }, updatedAt: now });
  b.set(doc(ana, 'users/ana'), { ...meta, keysEnc: keys }, { merge: true }); return assertSucceeds(b.commit()); })());
await t('owner reads own docs', assertSucceeds(Promise.all([getDoc(doc(ana, 'users/ana')), getDoc(doc(ana, 'users/ana/data/progress')), getDoc(doc(ana, 'users/ana/data/settings'))])));
await t('keysEnc: null allowed (Olvidé mi frase, merge)', assertSucceeds(setDoc(doc(ana, 'users/ana'), { keysEnc: null, updatedAt: now, schemaVersion: 1 }, { merge: true })));
await t('updatedAt as server timestamp allowed', assertSucceeds(updateDoc(doc(ana, 'users/ana'), { updatedAt: serverTimestamp() })));
await t('other user cannot read', assertFails(getDoc(doc(bob, 'users/ana'))));
await t('other user cannot read progress', assertFails(getDoc(doc(bob, 'users/ana/data/progress'))));
await t('other user cannot write', assertFails(setDoc(doc(bob, 'users/ana'), meta)));
await t('unauthenticated cannot read', assertFails(getDoc(doc(anon, 'users/ana'))));
await t('unauthenticated cannot write', assertFails(setDoc(doc(anon, 'users/x'), meta)));
await t('list on users denied', assertFails(getDocs(collection(ana, 'users'))));
await t('list on own data subcollection denied', assertFails(getDocs(collection(ana, 'users/ana/data'))));
await t('unknown top-level field denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, geminiKey: 'AIza...' })));
await t('progress embedded in meta denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, progress: {} })));
await t('updatedAt as string denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, updatedAt: 'ayer' })));
await t('schemaVersion missing denied', assertFails(setDoc(doc(ana, 'users/ana'), { updatedAt: now })));
await t('keysEnc with extra field (plain key) denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, keysEnc: { ...keys, geminiKey: 'x' } })));
await t('keysEnc with low iterations denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, keysEnc: { ...keys, iter: 1000 } })));
await t('keysEnc with huge ct denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, keysEnc: { ...keys, ct: 'x'.repeat(9000) } })));
await t('keysEnc salt as number denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, keysEnc: { ...keys, salt: 12345 } })));
await t('keysEnc as plain string denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, keysEnc: 'AIzaSy-plain' })));
await t('device too long denied', assertFails(setDoc(doc(ana, 'users/ana'), { ...meta, device: 'x'.repeat(200) })));
await t('progress with bad enc denied', assertFails(setDoc(doc(ana, 'users/ana/data/progress'), { z: 'a', enc: 'RAW', updatedAt: now })));
await t('progress over 1,000,000 chars denied', assertFails(setDoc(doc(ana, 'users/ana/data/progress'), { z: 'a'.repeat(1000001), enc: 'TK1', updatedAt: now })));
await t('progress extra field denied', assertFails(setDoc(doc(ana, 'users/ana/data/progress'), { z: 'a', enc: 'TK1', updatedAt: now, x: 1 })));
await t('settings with geminiKey denied', assertFails(setDoc(doc(ana, 'users/ana/data/settings'), { s: { geminiKey: 'AIza' }, updatedAt: now })));
await t('settings with openaiKey denied', assertFails(setDoc(doc(ana, 'users/ana/data/settings'), { s: { openaiKey: 'sk-' }, updatedAt: now })));
await t('settings not a map denied', assertFails(setDoc(doc(ana, 'users/ana/data/settings'), { s: 'x', updatedAt: now })));
await t('other doc id under data denied', assertFails(setDoc(doc(ana, 'users/ana/data/other'), { s: {}, updatedAt: now })));
await t('other subcollection denied', assertFails(setDoc(doc(ana, 'users/ana/extra/x'), { a: 1 })));
await t('other top-level collection denied', assertFails(setDoc(doc(ana, 'public/x'), { a: 1 })));
await t('owner can delete own data', assertSucceeds(deleteDoc(doc(ana, 'users/ana/data/progress'))));
await t('other user cannot delete', assertFails(deleteDoc(doc(bob, 'users/ana'))));
// ---- v2.10: contadores de las claves compartidas (quota/*), solo la cuenta de servidor ----
const SRV = 'R9hBV7CgH1geEUyZZT7wBkrIoE92', srv = env.authenticatedContext(SRV, { email: 'quota-server@tuki-speak.invalid' }).firestore();
const qd = db => doc(db, 'quota/2026-09-27_ana');
await t('server account creates a counter with increment + server time', assertSucceeds(setDoc(qd(srv), { gemini: increment(1), updatedAt: serverTimestamp() }, { merge: true })));
await t('server account increments another counter', assertSucceeds(setDoc(qd(srv), { azure: increment(1), updatedAt: serverTimestamp() }, { merge: true })));
await t('server account can refund (increment -1)', assertSucceeds(setDoc(qd(srv), { gemini: increment(-1), updatedAt: serverTimestamp() }, { merge: true })));
await t('user cannot write own counter (reset attempt)', assertFails(setDoc(qd(ana), { gemini: 0, updatedAt: serverTimestamp() }, { merge: true })));
await t('user cannot read counters', assertFails(getDoc(qd(ana))));
await t('unauthenticated cannot write counters', assertFails(setDoc(qd(anon), { gemini: 0, updatedAt: serverTimestamp() }, { merge: true })));
await t('user cannot delete counters', assertFails(deleteDoc(qd(ana))));
await t('server cannot delete counters', assertFails(deleteDoc(qd(srv))));
await t('server: unknown field denied', assertFails(setDoc(qd(srv), { gemini: increment(1), updatedAt: serverTimestamp(), note: 'x' }, { merge: true })));
await t('server: non-int counter denied', assertFails(setDoc(qd(srv), { live: 'x', updatedAt: serverTimestamp() }, { merge: true })));
await t('list on quota denied', assertFails(getDocs(collection(srv, 'quota'))));

// ---- v2.11: panel de administrador (dueño) + perfiles + comentarios ----
const OWN = { email: 'jrlopez6542@gmail.com', email_verified: true };
const owner = env.authenticatedContext('owner_uid', OWN).firestore();
const ownerUnverified = env.authenticatedContext('owner_uid', { email: 'jrlopez6542@gmail.com', email_verified: false }).firestore();
const ownerNoFlag = env.authenticatedContext('owner_uid', { email: 'jrlopez6542@gmail.com' }).firestore();
const fakeOwner = env.authenticatedContext('evil', { email: 'jrlopez6542@gmail.com.evil.com', email_verified: true }).firestore();
const anaE = env.authenticatedContext('ana', { email: 'ana@example.com', email_verified: true }).firestore();
const bobE = env.authenticatedContext('bob', { email: 'bob@example.com', email_verified: true }).firestore();
const prof = (extra = {}) => ({ name: 'Ana', email: 'ana@example.com', provider: 'google.com', app: '2.11.0', mode: 'shared', firstSeen: serverTimestamp(), lastActive: serverTimestamp(), ...extra });
const pd = (db, uid = 'ana') => doc(db, 'profiles/' + uid);
await t('profile: user creates own profile (server timestamps)', assertSucceeds(setDoc(pd(anaE), prof())));
await t('profile: user updates lastActive/app/mode (hourly touch, updateDoc)', assertSucceeds(updateDoc(pd(anaE), { name: 'Ana M', email: 'ana@example.com', provider: 'google.com', app: '2.11.1', mode: 'own', lastActive: serverTimestamp() })));
await t('profile: cannot change firstSeen on update', assertFails(updateDoc(pd(anaE), { firstSeen: serverTimestamp(), lastActive: serverTimestamp() })));
await t('profile: cannot recreate with setDoc (firstSeen would change)', assertFails(setDoc(pd(anaE), prof())));
await t('profile: cannot write another user\'s profile', assertFails(setDoc(pd(bobE, 'ana'), { ...prof(), email: 'bob@example.com' })));
await t('profile: email must match the sign-in token', assertFails(setDoc(pd(bobE, 'bob'), prof({ email: 'someone@else.com' }))));
await t('profile: extra field denied', assertFails(setDoc(pd(bobE, 'bob'), prof({ email: 'bob@example.com', admin: true }))));
await t('profile: bad provider denied', assertFails(setDoc(pd(bobE, 'bob'), prof({ email: 'bob@example.com', provider: 'anonymous' }))));
await t('profile: bad mode denied', assertFails(setDoc(pd(bobE, 'bob'), prof({ email: 'bob@example.com', mode: 'owner' }))));
await t('profile: client-chosen lastActive denied', assertFails(setDoc(pd(bobE, 'bob'), prof({ email: 'bob@example.com', lastActive: Timestamp.fromMillis(Date.now() + 86400e3) }))));
await t('profile: client-chosen firstSeen on create denied', assertFails(setDoc(pd(bobE, 'bob'), prof({ email: 'bob@example.com', firstSeen: Timestamp.fromMillis(1) }))));
await t('profile: name over 100 chars denied', assertFails(setDoc(pd(bobE, 'bob'), prof({ email: 'bob@example.com', name: 'x'.repeat(101) }))));
await t('profile: missing field denied', assertFails(setDoc(pd(bobE, 'bob'), { name: 'Bob', email: 'bob@example.com', firstSeen: serverTimestamp(), lastActive: serverTimestamp() })));
await t('profile: unauthenticated cannot create', assertFails(setDoc(pd(anon, 'x'), prof())));
await t('profile: bob creates his own (for listing)', assertSucceeds(setDoc(pd(bobE, 'bob'), prof({ name: 'Bob', email: 'bob@example.com', provider: 'password' }))));
await t('profile: user cannot read own profile', assertFails(getDoc(pd(anaE))));
await t('profile: user cannot read others', assertFails(getDoc(pd(bobE, 'ana'))));
await t('profile: user cannot list profiles', assertFails(getDocs(collection(anaE, 'profiles'))));
await t('profile: user cannot delete own profile', assertFails(deleteDoc(pd(anaE))));
await t('owner (verified) reads a profile', assertSucceeds(getDoc(pd(owner))));
await t('owner (verified) lists all profiles', (async () => { const r = await assertSucceeds(getDocs(query(collection(owner, 'profiles'), limit(1000)))); if (r.size !== 2) throw new Error('size ' + r.size); })());
await t('owner cannot delete profiles', assertFails(deleteDoc(pd(owner))));
await t('owner email NOT verified cannot list profiles', assertFails(getDocs(collection(ownerUnverified, 'profiles'))));
await t('owner email without email_verified claim cannot list', assertFails(getDocs(collection(ownerNoFlag, 'profiles'))));
await t('look-alike email cannot list profiles', assertFails(getDocs(collection(fakeOwner, 'profiles'))));
await t('owner creates own profile', assertSucceeds(setDoc(pd(owner, 'owner_uid'), prof({ name: 'Jonatan', email: 'jrlopez6542@gmail.com' }))));
await t('owner cannot write someone else\'s profile', assertFails(updateDoc(pd(owner, 'ana'), { name: 'x', email: 'jrlopez6542@gmail.com', provider: 'google.com', app: '1', lastActive: serverTimestamp() })));
// quota: el dueño lee y lista (panel); nadie más
await t('quota: owner reads a counter', assertSucceeds(getDoc(qd(owner))));
await t('quota: owner lists last 7 days (documentId range, like the panel)', (async () => { const r = await assertSucceeds(getDocs(query(collection(owner, 'quota'), where(documentId(), '>=', '2026-09-21_'), where(documentId(), '<', '2026-09-27_\uf8ff'), limit(5000)))); if (r.size !== 1) throw new Error('size ' + r.size); })());
await t('quota: unverified owner cannot list', assertFails(getDocs(collection(ownerUnverified, 'quota'))));
await t('quota: verified normal user cannot read', assertFails(getDoc(qd(anaE))));
await t('quota: verified normal user cannot list', assertFails(getDocs(collection(anaE, 'quota'))));
await t('quota: owner cannot write counters', assertFails(setDoc(qd(owner), { gemini: 0, updatedAt: serverTimestamp() }, { merge: true })));
await t('quota: owner cannot delete counters', assertFails(deleteDoc(qd(owner))));
// feedback
const fb = (extra = {}) => ({ uid: 'ana', email: 'ana@example.com', name: 'Ana', stars: 5, text: '¡Me encanta!', version: '2.11.0', createdAt: serverTimestamp(), ...extra });
let fbRef;
await t('feedback: signed-in user creates with own uid', (async () => { fbRef = await assertSucceeds(addDoc(collection(anaE, 'feedback'), fb())); })());
await t('feedback: empty text allowed (stars only)', assertSucceeds(addDoc(collection(anaE, 'feedback'), fb({ text: '', stars: 3 }))));
await t('feedback: 1000 chars allowed', assertSucceeds(addDoc(collection(bobE, 'feedback'), fb({ uid: 'bob', email: 'bob@example.com', text: 'x'.repeat(1000) }))));
await t('feedback: other uid denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ uid: 'bob' }))));
await t('feedback: email not matching token denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ email: 'jrlopez6542@gmail.com' }))));
await t('feedback: 0 stars denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ stars: 0 }))));
await t('feedback: 6 stars denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ stars: 6 }))));
await t('feedback: 3.5 stars denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ stars: 3.5 }))));
await t('feedback: 1001 chars denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ text: 'x'.repeat(1001) }))));
await t('feedback: extra field denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ admin: true }))));
await t('feedback: missing field denied', assertFails(addDoc(collection(anaE, 'feedback'), (({ version, ...r }) => r)(fb()))));
await t('feedback: client createdAt denied', assertFails(addDoc(collection(anaE, 'feedback'), fb({ createdAt: Timestamp.fromMillis(1) }))));
await t('feedback: unauthenticated denied', assertFails(addDoc(collection(anon, 'feedback'), fb())));
await t('feedback: user cannot read own feedback', assertFails(getDoc(doc(anaE, 'feedback/' + fbRef.id))));
await t('feedback: user cannot list feedback', assertFails(getDocs(collection(bobE, 'feedback'))));
await t('feedback: user cannot update', assertFails(updateDoc(doc(anaE, 'feedback/' + fbRef.id), { stars: 1 })));
await t('feedback: user cannot delete', assertFails(deleteDoc(doc(anaE, 'feedback/' + fbRef.id))));
await t('feedback: owner lists newest first (orderBy createdAt desc)', (async () => { const r = await assertSucceeds(getDocs(query(collection(owner, 'feedback'), orderBy('createdAt', 'desc'), limit(300)))); if (r.size !== 3) throw new Error('size ' + r.size); })());
await t('feedback: unverified owner cannot list', assertFails(getDocs(collection(ownerUnverified, 'feedback'))));
await t('feedback: owner cannot update', assertFails(updateDoc(doc(owner, 'feedback/' + fbRef.id), { stars: 1 })));
await t('feedback: owner deletes', assertSucceeds(deleteDoc(doc(owner, 'feedback/' + fbRef.id))));
await env.cleanup();
console.log(`RULES RESULTS: ${pass}/${pass + fail}`);
process.exit(fail ? 1 : 0);
